-- �?T SCHEMA HI?N T?I
ALTER SESSION SET CURRENT_SCHEMA = GK;

--------------------------------------------------------------------------------
-- T?O B?NG CO B?N
--------------------------------------------------------------------------------

-- B?NG LOP: TH�NG TIN L?P H?C
CREATE TABLE LOP (
    MALOP CHAR(6) PRIMARY KEY,
    TENLOP NVARCHAR2(50) NOT NULL,
    TGBATDAU DATE NOT NULL,
    TGKETTHUC DATE NOT NULL,
    TGHOC NVARCHAR2(50) NOT NULL,
    BAND VARCHAR2(20),
    SOBUOIHOC INT NOT NULL,
    SISO INT NOT NULL,
    MAGV CHAR(6),
    HOCPHI NUMBER(10,2) NOT NULL
);

-- B?NG GIAOVIEN: TH�NG TIN GI�O VI�N
CREATE TABLE GIAOVIEN (
    MAGV CHAR(6) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH CHAR(1) CONSTRAINT CK_GIOITINH_GV CHECK (GIOITINH IN ('M', 'F')),
    CMND CHAR(12) UNIQUE,
    SDT VARCHAR2(10) UNIQUE CONSTRAINT CK_SDT_GV CHECK (SDT LIKE '0%' AND LENGTH(SDT) = 10),
    EMAIL VARCHAR2(50) UNIQUE CONSTRAINT CK_EMAIL_GV CHECK (EMAIL LIKE '%@%.%'),
    DIACHI NVARCHAR2(50) NOT NULL,
    TRINHDO NVARCHAR2(50) NOT NULL,
    KINHNGHIEM NVARCHAR2(50) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    LUONGCOBAN NUMBER NOT NULL
);

-- B?NG HOCVIEN: TH�NG TIN H?C VI�N
CREATE TABLE HOCVIEN (
    MAHV CHAR(6) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH CHAR(1) CONSTRAINT CK_GIOITINH_HV CHECK (GIOITINH IN ('M', 'F')),
    SDT VARCHAR2(10) UNIQUE CONSTRAINT CK_SDT_HV CHECK (SDT LIKE '0%' AND LENGTH(SDT) = 10),
    EMAIL VARCHAR2(40) UNIQUE CONSTRAINT CK_EMAIL_HV CHECK (EMAIL LIKE '%@%.%'),
    DIACHI NVARCHAR2(40),
    TRINHDO NVARCHAR2(20) NOT NULL,
    NGHENGHIEP NVARCHAR2(10),
    MUCTIEU NVARCHAR2(10) NOT NULL
);

ALTER TABLE HOCVIEN MODIFY TRINHDO NVARCHAR2(20)

-- B?NG NHANVIEN: TH�NG TIN NH�N VI�N
CREATE TABLE NHANVIEN (
    MANV CHAR(6) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH CHAR(1) CONSTRAINT CK_GT_NV CHECK (GIOITINH IN ('M', 'F')),
    CMND CHAR(12) UNIQUE,
    SDT VARCHAR2(10) UNIQUE CONSTRAINT CK_SDT_NV CHECK (SDT LIKE '0%' AND LENGTH(SDT) = 10),
    EMAIL NVARCHAR2(50) UNIQUE CONSTRAINT CK_EMAIL_NV CHECK (EMAIL LIKE '%@%.%'),
    DIACHI NVARCHAR2(50) NOT NULL,
    KINHNGHIEM NVARCHAR2(50) NOT NULL,
    VITRI NVARCHAR2(50) NOT NULL,
    NGAYVAOLAM DATE NOT NULL,
    LUONGCOBAN NUMBER NOT NULL
);

-- B?NG LICHHOC: L?CH H?C CHI TI?T
CREATE TABLE LICHHOC (
    MALICHHOC CHAR(6) PRIMARY KEY,
    NGAYHOC NVARCHAR2(20) NOT NULL CONSTRAINT CK_NGAYHOC CHECK (NGAYHOC IN ('TH? 2','TH? 3','TH? 4','TH? 5','TH? 6','TH? 7')),
    BUOIHOC NVARCHAR2(50) NOT NULL CONSTRAINT CK_BUOIHOC CHECK (BUOIHOC IN ('CA 1','CA 2','CA 3','CA 4','CA 5')),
    MAPHONG VARCHAR2(20)
);

-- B?NG PHONGHOC
CREATE TABLE PHONGHOC (
    MAPHONG CHAR(6) PRIMARY KEY,
    TENPHONG NVARCHAR2(50) NOT NULL,
    SUCCHUA INT NOT NULL,
    LOAIPHONG NVARCHAR2(50) NOT NULL
);

-- B?NG THIETBI
CREATE TABLE THIETBI (
    MATB CHAR(6) PRIMARY KEY,
    TENTB NVARCHAR2(50) NOT NULL,
    TINHTRANG NVARCHAR2(50) NOT NULL,
    MAPHONG CHAR(6)
);

-- B?NG LICHHENTUVAN
CREATE TABLE LICHHENTUVAN (
    MALH CHAR(6) PRIMARY KEY,
    MANV CHAR(6),
    MAHV CHAR(6),
    NGAYHEN DATE NOT NULL,
    GIOHEN NVARCHAR2(30) NOT NULL,
    HINHTHUC NVARCHAR2(50) NOT NULL,
    TRANGTHAI NVARCHAR2(50) NOT NULL,
    GHICHU NVARCHAR2(50)
);

-- B?NG THONGBAO
CREATE TABLE THONGBAO (
    MATB CHAR(6) PRIMARY KEY,
    TIEUDE NVARCHAR2(50) NOT NULL,
    NOIDUNG NVARCHAR2(50) NOT NULL,
    LOAITB NVARCHAR2(50) NOT NULL,
    NGAYGUI DATE NOT NULL,
    MANV CHAR(6)
);

-- B?NG KHUYENMAI
CREATE TABLE KHUYENMAI (
    MAKM CHAR(6) PRIMARY KEY,
    TENKM NVARCHAR2(50) NOT NULL,
    MOTA NVARCHAR2(50) NOT NULL,
    LOAIKM NVARCHAR2(500) NOT NULL CONSTRAINT CK_LOAIKM CHECK(LOAIKM IN ('Uu dai nhom', 'Hoc mien phi cho hoc vien xuat sac', 'Ngay Vang Giam Gia')),
    GIATRIKM NVARCHAR2(50) NOT NULL,
    NGAYBD DATE NOT NULL,
    NGAYKT DATE NOT NULL,
    MANV CHAR(6)
);

-- B?NG BAITAP
CREATE TABLE BAITAP (
    MABT CHAR(6) PRIMARY KEY,
    TENBT NVARCHAR2(50) NOT NULL,
    LOAIBT NVARCHAR2(50) NOT NULL,
    DIEMMAX NUMBER(5,2) NOT NULL
);

-- B?NG DANGKYLOP
CREATE TABLE DANGKYLOP (
    MAHV CHAR(6),
    MALOP CHAR(6),
    TGDANGKY DATE NOT NULL,
    KETQUAHOC NUMBER(5,2),
    DIEMTONGKET NUMBER(5,2),
    SOTIENTT NUMBER NOT NULL,
    PHUONGTHUC VARCHAR2(20) NOT NULL,
    PRIMARY KEY (MAHV, MALOP)
);

-- B?NG DIEMDANH
CREATE TABLE DIEMDANH (
    MAHV CHAR(6),
    MALOP CHAR(6),
    MALICHHOC CHAR(6),
    NGAYDIEMDANH DATE NOT NULL,
    TRANGTHAI VARCHAR2(20) NOT NULL CONSTRAINT CK_TT_DD CHECK (TRANGTHAI IN ('1','2',NULL)),
    GHICHU NVARCHAR2(50),
    PRIMARY KEY (MAHV, MALOP, MALICHHOC)
);

-- B?NG PHANCONGGIANGDAY
CREATE TABLE PHANCONGGIANGDAY (
    MAGV CHAR(6),
    MALOP CHAR(6),
    MALICHHOC CHAR(6),
    NGAYPHANCONG DATE,
    TINHTRANG VARCHAR2(20) NOT NULL,
    PRIMARY KEY (MAGV, MALOP, MALICHHOC)
);

-- B?NG GIAOBAITAP
CREATE TABLE GIAOBAITAP (
    MAGV CHAR(6),
    MALOP CHAR(6),
    MABAITAP CHAR(6),
    NGAYGIAO DATE,
    DEADLINE DATE,
    PRIMARY KEY (MAGV, MALOP, MABAITAP)
);

-- B?NG LAMBAITAP
CREATE TABLE LAMBAITAP (
    MAHV CHAR(6),
    MALOP CHAR(6),
    NGAYLAM DATE,
    MABAITAP CHAR(6),
    PRIMARY KEY (MAHV, MALOP, MABAITAP)
);

-- B?NG SUDUNGKHUYENMAI
CREATE TABLE SUDUNGKHUYENMAI (
    MAKM CHAR(6),
    MAHV CHAR(6),
    MALOP CHAR(6),
    NGAYSUDUNG DATE
);

--------------------------------------------------------------------------------
-- T?O C�C KH�A NGO?I
--------------------------------------------------------------------------------

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE THIETBI ADD CONSTRAINT FK_TB_PHONGHOC FOREIGN KEY (MAPHONG) REFERENCES PHONGHOC(MAPHONG);
ALTER TABLE LICHHENTUVAN ADD CONSTRAINT FK_LHTV_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE LICHHENTUVAN ADD CONSTRAINT FK_LHTV_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);
ALTER TABLE THONGBAO ADD CONSTRAINT FK_TB_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE KHUYENMAI ADD CONSTRAINT FK_KM_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE DANGKYLOP ADD CONSTRAINT FK_DKL_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);
ALTER TABLE DANGKYLOP ADD CONSTRAINT FK_DKL_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE DIEMDANH ADD CONSTRAINT FK_DD_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);
ALTER TABLE DIEMDANH ADD CONSTRAINT FK_DD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE DIEMDANH ADD CONSTRAINT FK_DD_LH FOREIGN KEY (MALICHHOC) REFERENCES LICHHOC(MALICHHOC);
ALTER TABLE PHANCONGGIANGDAY ADD CONSTRAINT FK_PCGD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE PHANCONGGIANGDAY ADD CONSTRAINT FK_PCGD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE PHANCONGGIANGDAY ADD CONSTRAINT FK_PCGD_LH FOREIGN KEY (MALICHHOC) REFERENCES LICHHOC(MALICHHOC);
ALTER TABLE GIAOBAITAP ADD CONSTRAINT FK_GBT_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE GIAOBAITAP ADD CONSTRAINT FK_GBT_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE GIAOBAITAP ADD CONSTRAINT FK_GBT_BT FOREIGN KEY (MABAITAP) REFERENCES BAITAP(MABT);
ALTER TABLE LAMBAITAP ADD CONSTRAINT FK_LBT_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);
ALTER TABLE LAMBAITAP ADD CONSTRAINT FK_LBT_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE LAMBAITAP ADD CONSTRAINT FK_LBT_BT FOREIGN KEY (MABAITAP) REFERENCES BAITAP(MABT);
ALTER TABLE SUDUNGKHUYENMAI ADD CONSTRAINT FK_SDKM_KM FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM);
ALTER TABLE SUDUNGKHUYENMAI ADD CONSTRAINT FK_SDKM_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);
ALTER TABLE SUDUNGKHUYENMAI ADD CONSTRAINT FK_SDKM_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);


